use lansa
INSERT INTO [VWBPLIBF].[KLASSE] (ADMCODE, KLSCODE, KLSACODE, KLSOMS, KLSNAC, KLSOPSCH, "@@UPID")
VALUES ('RPO', 1, 'I', 'I', 0, 0, 4);

INSERT INTO [VWBPLIBF].KLASSE (ADMCODE, KLSCODE, KLSACODE, KLSOMS, KLSNAC, KLSOPSCH, "@@UPID")
VALUES ('RPO', 2, '2', '2', 0, 0, 3);

INSERT INTO [VWBPLIBF].KLASSE (ADMCODE, KLSCODE, KLSACODE, KLSOMS, KLSNAC, KLSOPSCH, "@@UPID")
VALUES ('RPO', 3, 'INDUSTRIE', 'Industrie', 0, 0, 4);

INSERT INTO [VWBPLIBF].KLASSE (ADMCODE, KLSCODE, KLSACODE, KLSOMS, KLSNAC, KLSOPSCH, "@@UPID")
VALUES ('RPO', 4, 'MILIEUKEUR', 'mk......................................', 0, 0, 3);

INSERT INTO [VWBPLIBF].KLASSE (ADMCODE, KLSCODE, KLSACODE, KLSOMS, KLSNAC, KLSOPSCH, "@@UPID")
VALUES ('RPO', 5, 'OMPAK', 'Ompak', 0, 0, 1);

