USE `LANSA`;

CREATE TABLE `VTLI0036D`(
	`V_MYS_ID` int NOT NULL,
	`V_MYS_NAME` nvarchar(50) NULL,
	`V_MYS_SURNAME` char(10) NULL,
	`V_MYS_LASTNAME` nchar(10) NULL,
	`V_MYS_DATE` datetime(3) NULL,
	`V_MYS_SALARY` Double NULL,
	`V_MYS_ACTIVE` Tinyint NULL,
	`V_MYS_DESC` Longtext NULL,
	`V_MYS_TAG` Char(36) NULL,
	`V_MYS_TIME` time(6) NULL,
	`V_MYS_RAWDATA` binary(50) NULL,
	`V_MYS_DATA` varchar(50) NULL,
	`V_MYS_CODE` numeric(18, 0) NULL,
	`V_MYS_XML` Longtext NULL,
 CONSTRAINT `PK_VTLI0036D` PRIMARY KEY 
(
	`V_MYS_ID` ASC
) 
) ;

