ALTER SESSION SET CURRENT_SCHEMA = LANSA;



CREATE TABLE VTLI0036C(
	V_ORA_ID Number(10) NOT NULL,
	V_ORA_NAME Nvarchar2(50) NULL,
	V_ORA_SURNAME char(10) NULL,
	V_ORA_LASTNAME nchar(10) NULL,
	V_ORA_DATE Timestamp(3) NULL,
	V_ORA_SALARY Binary_double NULL,
	V_ORA_ACTIVE Number(1) NULL,
	V_ORA_DESC Clob NULL,
	V_ORA_TAG Char(36) NULL,
	V_ORA_TIME Timestamp(7) NULL,
	V_ORA_RAWDATA Raw(50) NULL,
	V_ORA_DATA Varchar2(50) NULL,
	V_ORA_CODE Number(18, 0) NULL,
 CONSTRAINT PK_VTI0036C PRIMARY KEY
(
	V_ORA_ID
)
);

