ALTER SESSION SET CURRENT_SCHEMA = LANSA;



CREATE TABLE VWBPLIBF.VTLI0036C(
	V_ID Number(10) NOT NULL,
	V_NAME Nvarchar2(50) NULL,
	V_SURNAME char(10) NULL,
	V_LASTNAME nchar(10) NULL,
	V_DATE Timestamp(3) NULL,
	V_SALARY Binary_double NULL,
	V_ACTIVE Number(1) NULL,
	V_DESC Clob NULL,
	V_TAG Char(36) NULL,
	V_TIME Timestamp(7) NULL,
	V_RAWDATA Raw(50) NULL,
	V_DATA Varchar2(50) NULL,
	V_CODE Number(18, 0) NULL,
	V_XML Xmltype NULL,
 CONSTRAINT PK_VTLI0036C PRIMARY KEY
(
	V_ID
)
) ;
